---
    - hosts: local
      become: yes
      vars:
        app_name: BuhoCleaner
        app_url: https://www.drbuho.com/download/buhocleaner.dmg
        installer_type: app
        install_method: dmg
        download_file_type: dmg
      roles:
        - setup
        - installer
        - cleanup
       