---
    - hosts: local
      become: yes
      vars:
        app_name: Little Snitch
        app_url: https://www.obdev.at/downloads/littlesnitch/LittleSnitch-5.4.1.dmg
        installer_type: app
        install_method: dmg
        download_file_type: dmg
      roles:
        - setup
        - installer
        - cleanup
       